name = "internet-tracker"
main = "src/worker.js"
compatibility_date = "2024-09-25"

[[d1_databases]]
binding = "DB"
database_name = "internet-tracker-db"
database_id = "90ab6295-c6df-473a-8492-9bb995cc666a"